export const ALL_BIDDING_REQUEST = "ALL_BIDDING_REQUEST";
export const ALL_BIDDING_SUCCESS = "ALL_BIDDING_SUCCESS";
export const ALL_BIDDING_FAIL = "ALL_BIDDING_FAIL";

export const NEW_BIDDING_REQUEST = "NEW_BIDDING_REQUEST";
export const NEW_BIDDING_SUCCESS = "NEW_BIDDING_SUCCESS";
export const NEW_BIDDING_RESET = "NEW_BIDDING_RESET";
export const NEW_BIDDING_FAIL = "NEW_BIDDING_FAIL";

export const UPDATE_BIDDING_REQUEST = "UPDATE_BIDDING_REQUEST";
export const UPDATE_BIDDING_SUCCESS = "UPDATE_BIDDING_SUCCESS";
export const UPDATE_BIDDING_RESET = "UPDATE_BIDDING_RESET";
export const UPDATE_BIDDING_FAIL = "UPDATE_BIDDING_FAIL";